// react/demo/02-project/redux-todo-app/src/containers/todo/index.jsx
import React from 'react';
import TodoHeader from '../../components/todo-header';
import TodoList from '../../components/todo-list';
import TodoFooter from '../../components/todo-footer';
import './index.css';

export default () => (
  <div className="todo-container">
    <div className="todo-wrap">
      <TodoHeader/>
      <TodoList/>
      <TodoFooter/>
    </div>
  </div>
);

// vue/demo/02-project/vuex-todo-app/src/containers/todo/index.vue
<template>
  <div class="todo-container">
    <div class="todo-wrap">
      <todo-header/>
      <todo-list/>
      <todo-footer/>
    </div>
  </div>
</template>

<script>
  import { TodoHeader, TodoList, TodoFooter } from '@/components'

  export default {
    mounted() {
      this.$store.dispatch('getAllTodos')
    },
    components: {
      TodoHeader,
      TodoList,
      TodoFooter
    }
  }
</script>

<style>
  .todo-container {
    width: 600px;
    margin: 0 auto;
  }
  .todo-container .todo-wrap {
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
  }
</style>
